t/generate_random_genomefiles.pl
One new testing file has been added to download a random bacteria genome in GenBank format and FASTA format. And generate config file for them
=> add a new testing script to generate config files

src/us/kbase/genbank/ConvertGBK.java, src/us/kbase/genbank/GenometoGbk.java
Reverts kbase/transform#29
Fails make, errors with java build need to be resolved.
=> Revert "more upgrades to genbank output"

lib/Bio/KBase/Transform/ScriptHelpers.pm
Adding utility functions for GTO conversion for use in genome transforms.
=> Adding utility functions for GTO conversion

src/us/kbase/genbank/GenometoGbk.java
The KBase Genome to Genbank converter now in genome browsers e.g. Artemis
=> gbk output loads in artemis viewer again

t/data_url
I added a file, which contains some url linking to GenBank file or sequence reads file
Those url can be used for testing.
=> testing data url

scripts/trns_transform_KBaseBiochem.CSV-to-KBaseBiochem.Media.pl, scripts/trns_transform_KBaseBiochem.Excel-to-KBaseBiochem.Media.pl, scripts/trns_transform_KBaseFBA.CSV-to-KBaseFBA.FBAModel.pl, scripts/trns_transform_KBaseFBA.Excel-to-KBaseFBA.FBAModel.pl, scripts/trns_transform_KBaseFBA.SBML-to-KBaseFBA.FBAModel.pl, scripts/trns_transform_KBasePhenotypes.CSV-to-KBasePhenotypes.PhenotypeSet.pl
=> Updating scripts that use fbaModelServices for proper capture of messages

scripts/trns_transform_KBaseBiochem.Excel-to-KBaseBiochem.Media.pl, scripts/trns_transform_KBaseFBA.CSV-to-KBaseFBA.FBAModel.pl, scripts/trns_transform_KBaseFBA.Excel-to-KBaseFBA.FBAModel.pl, scripts/trns_transform_KBaseFBA.SBML-to-KBaseFBA.FBAModel.pl, scripts/trns_transform_KBasePhenotypes.CSV-to-KBasePhenotypes.PhenotypeSet.pl, scripts/trns_transform_Transcripts.FASTA-to-KBaseGenomes.Genome.pl, scripts/trns_validate_KBaseBiochem.Excel.pl, scripts/trns_validate_KBaseFBA.CSV.pl, scripts/trns_validate_KBaseFBA.Excel.pl, scripts/trns_validate_KBaseFBA.SBML.py
I tried to use script_utils.py for my SBML validation script, but I don't have the python clients for the handle service installed in my environment, and they're not available in the handle_service repository, or so it seems. Can you test trns_validate_KBaseFBA.SBML.py for me?
=> Update of logging for many scripts

src/us/kbase/genbank/ConvertGBK.java, src/us/kbase/genbank/GbkUploader.java, src/us/kbase/genbank/ValidateGBK.java
test for upload file size and create ContigSet
=> named arguments changes

plugins/configs/KBaseGenomes.Genome_to_ContigFasta.json, plugins/configs/KBaseGenomes.Genome_to_EMBL.json, plugins/configs/KBaseGenomes.Genome_to_FeatureDNA.json, plugins/configs/KBaseGenomes.Genome_to_FeatureData.json, plugins/configs/KBaseGenomes.Genome_to_GBK.json, plugins/configs/KBaseGenomes.Genome_to_GBKMerged.json, plugins/configs/KBaseGenomes.Genome_to_GFF.json, plugins/configs/KBaseGenomes.Genome_to_ProteinFasta.json, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-ContigFasta.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-EMBL.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-FeatureDNA.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-FeatureData.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-GBK.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-GBKMerged.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-GFF.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Genome-to-ProteinFasta.pl
Initial pull request for the changes discussed this afternoon. In the absence of an output file specified we write files named with the object name and the appropriate suffix.
I don't know if we've standardized the external types; these are all easy to change when we do since the configs and scripts are generated from templates and a table of type information.
=> Initial version of new interface.

src/us/kbase/genbank/ConvertGBK.java
=> new command line args for ConvertGBK

lib/Bio/KBase/Transform/ScriptHelpers.pm, plugins/scripts/download/trns_transform_KBaseBiochem.Media-to-CSV.pl, plugins/scripts/download/trns_transform_KBaseFBA.FBA-to-CSV.pl, plugins/scripts/download/trns_transform_KBaseFBA.FBAModel-to-CSV.pl, plugins/scripts/download/trns_transform_KBaseFBA.FBAModel-to-SBML.pl, plugins/scripts/download/trns_transform_KBaseGenomes.Pangenome-to-CSV.pl, plugins/scripts/download/trns_transform_KBasePhenotypes.PhenotypeSet-to-CSV.pl, plugins/scripts/download/trns_transform_KBasePhenotypes.PhenotypeSimulationSet-to-CSV.pl
Added download script for PanGenome
=> Added download script for PanGenome

plugins/scripts/upload/trns_transform_seqs_to_KBaseAssembly_type.pl
This handles uploaders for:
FASTA/FASTQ to PairedEndLibrary
FASTA/FASTQ to SingleEndLibrary
FASTA to ReferenceAssembly
=> add script for uploading KBaseAssembly types

lib/biokbase/Transform/script_utils.py
Reverts kbase/transform#93, belongs in develop
=> Revert "Fix to handle shock URLs that are not production"

lib/biokbase/Transform/script_utils.py
PR to the correct branch this time
=> Fix to handle shock URLs that are not production

src/us/kbase/genbank/GbkFeature.java, src/us/kbase/genbank/GenometoGbk.java
improved object time and size formatting
=> fixed case of no aliases

src/us/kbase/genbank/ConvertGBK.java, src/us/kbase/genbank/GbkFeature.java, src/us/kbase/genbank/GbkUploader.java, src/us/kbase/genbank/GenometoGbk.java
populating aliases if available
fixed location on minus strand
=> populating taxonomy id if available

src/us/kbase/genbank/ConvertGBK.java, src/us/kbase/genbank/GbkUploader.java, src/us/kbase/genbank/GenometoGbk.java, src/us/kbase/genbank/ValidateGBK.java
correct object naming for upload
=> support multiple genbank file download

plugins/configs/TSV.Expression_to_KBaseFeatureValues.ExpressionMatrix.json, plugins/scripts/upload/trns_transform_TSV_Exspression_to_KBaseFeatureValues_ExpressionMatrix.py
Part of Narrative pipeline related to KBase feature values repo.
=> Expression TSV-file uploader (v.0.1).

plugins/scripts/taskrunners/trns_upload_taskrunner.py
Sends back stderr from the job instead of a stack trace, also does not complete the job after the exception was reported because the job was already marked as completed.
=> update upload taskrunner for propagating stderr back on upload failure

plugins/configs/FASTA.DNA.Assembly_to_KBaseGenomeAnnotations.Assembly.json, plugins/configs/Genbank.Genome_to_KBaseGenomeAnnotations.GenomeAnnotation.json, plugins/scripts/upload/trns_transform_FASTA_DNA_Assembly_to_KBaseGenomeAnnotations_Assembly.py, plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py
Added better coordinate handling for atypical coordinates. Also add better locus line handling.
Added .dat to list of valid extension, which is what ensembl uses
Added some missing optional fields I could fill in
Added logic if no Organism line
=> Updates to GenomeAnnotation and Assembly data type uploads

t/demo/bin/upload_script_test.py
Still some other cleanup and enhancements to be done in this file, but printing out the UJS messages is needed for testing purposes.
=> monitor UJS messages during script testing

plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py
Retrieve the Taxon object to check lineage.  Allow viruses and viroids genomes to be of type RNA
=> Allow for Viruses and Viroids genome to be of molecule type RNA

plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py
Two issues - bug in publications for unsupported publication keys. Fixed second issue of unsupported section (Contigs) in the features section
=> KBase 3079 fix. 

plugins/scripts/upload/trns_transform_FASTA_DNA_Assembly_to_KBaseGenomes_ContigSet.py
KBASE3041, KBASE1681, KBASE2916 fix.
Note this does not mean this issue can not still happen as the core issue is the size limit of the annotation.  However this is more accurate and should stop the majority of these cases from happening.
=> Contig set upload fasta key issue fixed.

build.xml, plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomes_Genome.py, plugins/scripts/upload/trns_transform_TSV_Chromatography_to_KBaseEnigmaMetals_ChromatographyMatrix.py, plugins/scripts/upload/trns_transform_TSV_Growth_to_KBaseEnigmaMetals_GrowthMatrix.py, plugins/scripts/upload/trns_transform_TSV_WellSample_to_KBaseEnigmaMetals_WellSampleMatrix.py, src/us/kbase/kbaseenigmametals/ChromatographyDataImporter.java, src/us/kbase/kbaseenigmametals/ChromatographyMatrix.java, src/us/kbase/kbaseenigmametals/ChromatographyMatrixUploader.java, src/us/kbase/kbaseenigmametals/DataMatrix.java, src/us/kbase/kbaseenigmametals/DataMatrixUploader.java, src/us/kbase/kbaseenigmametals/FloatMatrix2D.java, src/us/kbase/kbaseenigmametals/GrowthDataImporter.java, src/us/kbase/kbaseenigmametals/GrowthMatrix.java, src/us/kbase/kbaseenigmametals/GrowthMatrixUploader.java, src/us/kbase/kbaseenigmametals/Matrix2DMetadata.java, src/us/kbase/kbaseenigmametals/PropertyValue.java, src/us/kbase/kbaseenigmametals/WellSampleDataImporter.java, src/us/kbase/kbaseenigmametals/WellSampleMatrix.java, src/us/kbase/kbaseenigmametals/WellSampleMatrixUploader.java, src/us/kbase/kbaseenigmametals/WsDeluxeUtil.java
Matt, please merge these changes. Roman suggested to put all java source files into transform repository instead of separate jar file in the jars repo.
=> uploaders for ChromatographyMatrix, GrowthMatrix and WellSampleMatrix

plugins/scripts/upload/trns_transform_TSV_Phenotypes_to_KBasePhenotypes_PhenotypeSet.pl
fix for "workspace not found" in KBASE-2622
=> fix for fbaurl and wsurl; need to use reference in GetOptions

lib/biokbase/Transform/script_utils.py
=> Allow for case when to Arg descriptions have the same ending

deps/pylib.sh, deps/sudo_install_tables.sh, lib/biokbase/Transform/script_utils.py, plugins/configs/mzML.LCMS_to_MetaboliteAtlas2_MAFileInfo.json, plugins/scripts/upload/trns_transform_mzML_LCMS_to_MetaboliteAtlas2_MAFileInfo.py
Provides a config and script for loading mzML files to the workspace.
=> Add upload script for mzML files

plugins/scripts/upload/trns_transform_FASTA_DNA_Assembly_to_KBaseGenomes_ContigSet.py
=> Fixes for contigset upload, fixed inefficiency with fasta key uniqueness check and optimized valid bases check

plugins/configs/FASTA.DNA.Assembly_to_KBaseGenomeAnnotations.Assembly.json, plugins/configs/Genbank.Genome_to_KBaseGenomeAnnotations.GenomeAnnotation.json, plugins/scripts/upload/trns_transform_FASTA_DNA_Assembly_to_KBaseGenomeAnnotations_Assembly.py, plugins/scripts/upload/trns_transform_FASTA_DNA_Assembly_to_KBaseGenomes_ContigSet.py, plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomeAnnotations_GenomeAnnotation.py
Hopefully they are correct now
=> Updated the config files for annotation and assembly.  

lib/biokbase/Transform/handler_utils.py, plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomes_Genome.py
Rewrote the handler subprocess calls to use pty instead of pipes.  Using regular files would have resolved the deadlock, but due to buffering issues outside of transform and python, you would not get any status updates until after the process completed, in the meantime it would appear stuck.
This required adding threads to consume the stdout and stderr streams without being blocked by buffering, then writing those streams to file on disk in order to pick them at the end of the run for reporting purposes, since we can wait for buffering.
There were smaller changes needed in the Genome upload wrapper script, mainly to drop defining stdout and stderr for the call to Java, and instead inherit those from the parent process, leaving the stream monitoring to the parent.  This simplifies what is …
=> resolving deadlocks and buffering issues for Genome upload

src/us/kbase/genbank/ConvertGBK.java, src/us/kbase/genbank/GbkFeature.java, src/us/kbase/genbank/GbkParser.java, src/us/kbase/genbank/GbkUploader.java, src/us/kbase/genbank/GenometoGbk.java, src/us/kbase/genbank/ValidateGBK.java
- fix for uploading with taxonomy version
- aborts upload if no contig sequence
=> 1) taxonomy version + 2) abort upload with no contig sequence

plugins/scripts/validate/trns_validate_Sequence.py
Eliminate usage of PIPE for Popen, also switch logger to stdout.
=> updating validate sequence script to remove PIPEs

lib/biokbase/Transform/handler_utils.py, plugins/scripts/taskrunners/trns_upload_taskrunner.py, plugins/scripts/upload/trns_transform_Genbank_Genome_to_KBaseGenomes_Genome.py, plugins/scripts/validate/trns_validate_Sequence.py, t/demo/bin/upload_script_test.py
After navigating the dungeons of KBase, finally resolved some issues here and put in some more error checking and cleanup for sequence validation.  Updated the script runner to make debugging easier.
=> Updates for upload handling, Genome upload, sequence validation

src/us/kbase/genbank/ConvertGBK.java, src/us/kbase/genbank/GbkParser.java, src/us/kbase/genbank/GbkUploader.java, src/us/kbase/genbank/GenometoGbk.java
- LCOUS line contig length
- duplicate ORIGIN line if one contig
- edge cage of single base in last line of ORIGIN
- simplify logic for file extension appending in ConvertGBK
=> gbk download fixes:

lib/biokbase/Transform/handler_utils.py
Calling Popen.poll() was not thread safe, and was returning non-deterministic values for the subprocess return code.  This update monitors the task completion from the main thread as usual, but now uses a thread event to communicate that the subprocess has completed before calling thread.join().
=> fix for unstable Popen exit codes

plugins/scripts/convert/trns_transform_KBaseFile_AssemblyFile_to_KBaseGenomes_ContigSet.py
Port Jason's changes from the FASTA->ContigSet uploader to the KBaseFile.AssemblyFile->ContigSet converter
=> Port over Jason's fixes to the contig uploader + some cleanup
